[2023-03-22 08:11:27] [1] [INFO] 
============= Test configuration =============
url=https://www.gsmarena.com
env=DEMO
selenium_url=http://localhost:4444/wd/hub
auto_screenshot=true
project_report_directory=./reports
max_screen_history=10
localization_encoding=UTF-8
language=en_US
selenium_url=http://localhost:4444/wd/hub

------------- Driver capabilities -----------
capabilities.providerOptions=options
capabilities.browserName=chrome
================================================

[2023-03-22 08:11:28] [1] [WARN] Reporting disabled: using no op test run registrar
[2023-03-22 08:11:30] [1] [INFO] [TestNG] Running:
  C:\Users\oleksii.shevtsov\AppData\Local\JetBrains\IdeaIC2021.3\temp-testng-customsuite.xml

[2023-03-22 08:11:30] [1] [INFO] Set thread-count=1
[2023-03-22 08:11:30] [1] [INFO] Set data-provider-thread-count=1
[2023-03-22 08:11:30] [1] [INFO] CARINA_CORE_VERSION: 8.0.7
[2023-03-22 08:11:30] [1] [ERROR] TEST [Test - testSignUpUser [L01]] FAILED at [22:11:30 2023-03-22] - 
[public void SignUpTest.testSignUpUser()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: testSignUpUser([])
Arguments: [(java.lang.String) lubs,(java.lang.String) aaa@gmail.com,(java.lang.String) jkloi890]

org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
org.testng.internal.Parameters.injectParameters(Parameters.java:918)
org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
org.testng.TestRunner.privateRun(TestRunner.java:806)
org.testng.TestRunner.run(TestRunner.java:601)
org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
org.testng.SuiteRunner.run(SuiteRunner.java:330)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
org.testng.TestNG.runSuites(TestNG.java:1099)
org.testng.TestNG.run(TestNG.java:1067)
com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
[2023-03-22 08:11:30] [1] [INFO] INFO: '**************** Test execution summary ****************'.
[2023-03-22 08:11:30] [1] [INFO] RESULT #1: TEST [Test - testSignUpUser [L01]] FAIL [log=file://C:\Users\oleksii.shevtsov\IdeaProjects\Test\.\reports\1679515888035/1679515888035/test.log]
